name: Site IPs

on:
  #schedule:
  #  - cron: '0 0/12 * * *' # 每12小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the site_ips script
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_DOMAIN_NAME: ${{ secrets.CF_DOMAIN_NAME }}
        CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
      run: python site_ips.py

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add site_ips.txt
        git commit -m "Update site_ips.txt" || echo "No changes to commit"
        git push origin main
